title: Fontra Docs
email: gustavo@hipertipo.com
description: Fontra user documentation
baseurl: ""
url: https://gferreira.github.io/fontra-docs

collections:
  explanations:
    output: true
    permalink: /:path/
  how-tos:
    output: true
    permalink: /:path/
  reference:
    output: true
    permalink: /:path/
  tutorials:
    output: true
    permalink: /:path/

markdown: kramdown

version: 0.1

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll_tidy:
  exclude: []
  # ignore_env: development
  compress_html: false
